version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smart_factory_pg
    environment:
      POSTGRES_USER: factory_admin
      POSTGRES_PASSWORD: factory_password
      POSTGRES_DB: smart_factory
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  influxdb:
    image: influxdb:2.7
    container_name: smart_factory_influx
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: factory_admin
      DOCKER_INFLUXDB_INIT_PASSWORD: factory_password
      DOCKER_INFLUXDB_INIT_ORG: factory_org
      DOCKER_INFLUXDB_INIT_BUCKET: telemetry_bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: super-secret-admin-token
    volumes:
      - influxdata:/var/lib/influxdb2

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: smart_factory_mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  pgdata:
  influxdata:
